"""V1 API models."""

from magick_mind.models.v1.artifact import (
    Artifact,
    ArtifactStatusEnum,
    ArtifactWebhookPayload,
    DeleteArtifactResponse,
    DownloadUrlResponse,
    FinalizeArtifactRequest,
    FinalizeArtifactResponse,
    GetArtifactResponse,
    ListArtifactsResponse,
    PresignArtifactRequest,
    PresignArtifactResponse,
    ScopedPresignRequest,
)
from magick_mind.models.v1.blueprint import (
    Blueprint,
    CloneBlueprintRequest,
    CreateBlueprintRequest,
    HydratedBlueprint,
    HydratedBlueprintTrait,
    ListBlueprintsResponse,
    PatchBlueprintRequest,
    UpdateBlueprintRequest,
    ValidateBlueprintRequest,
    ValidateBlueprintResponse,
    ValidationError as BlueprintValidationError,
)
from magick_mind.models.v1.chat import (
    ChatAck,
    ChatSendRequest,
    ChatSendResponse,
)
from magick_mind.models.v1.corpus import (
    AddArtifactsRequest,
    AddArtifactsResponse,
    ArtifactStatus,
    Chunk,
    Corpus,
    CorpusArtifactItem,
    CreateCorpusRequest,
    Entity,
    IngestionStatus,
    ListArtifactStatusesResponse,
    ListCorpusResponse,
    QueryCorpusResponse,
    QueryMetadata,
    Reference,
    Relationship,
    UpdateCorpusRequest,
)
from magick_mind.models.v1.end_user import (
    AttachPersonaRequest,
    CreateEndUserRequest,
    EndUser,
    MintEndUserTokenRequest,
    MintEndUserTokenResponse,
    ParticipantType,
    QueryEndUserResponse,
    RefreshEndUserTokenRequest,
    RevokeEndUserTokenRequest,
    RevokeEndUserTokenResponse,
    SetAgentPersonaVersionRequest,
    UpdateEndUserRequest,
)
from magick_mind.models.v1.episode import (
    EndUserProcessEpisodeRequest,
    Episode,
    ListEpisodesByDateRangeResponse,
    ProcessEpisodeRequest,
    ProcessEpisodeResponse,
    SearchEpisodesResponse,
)
from magick_mind.models.v1.history import ChatHistoryMessage, HistoryResponse
from magick_mind.models.v1.api_keys import (
    ApiKey,
    CreateApiKeyRequest,
    CreateApiKeyResponse,
    DeleteApiKeyResponse,
    KeyResponse,
    ListApiKeysResponse,
    UpdateApiKeyRequest,
    UpdateApiKeyResponse,
)
from magick_mind.models.v1.mindspace import (
    CONTROL_MESSAGE_TYPES,
    SIGNAL_MESSAGE_TYPES,
    AddMindSpaceUsersRequest,
    ChatHistoryItem,
    ChatHistoryParams,
    ContextPrepareResponse,
    CorpusChunk,
    CorpusInfo,
    CorpusParams,
    CreateMindSpaceRequest,
    EndUserSendMessageRequest,
    FetcherParams,
    GetMindSpaceListResponse,
    LivekitJoinResponse,
    LivekitTokenResponse,
    MessageType,
    MindSpace,
    MindSpaceType,
    MindspaceMessagesResponse,
    SendMessageRequest,
    UpdateMindSpaceRequest,
    is_control_message,
    is_signal_message,
)
from magick_mind.models.v1.persona import (
    CreatePersonaFromBlueprintRequest,
    CreatePersonaRequest,
    CreatePersonaVersionRequest,
    ListPersonaVersionsResponse,
    Persona,
    PersonaVersion,
    PersonaWithVersion,
    PreparePersonaRequest,
    PrepareAgentPersonaResponse,
    PreparePersonaResponse,
    UpdatePersonaRequest,
)
from magick_mind.models.v1.personality import (
    BlueprintTrait,
    Boundary,
    Constraint,
    DomainRates,
    DyadicConfig,
    GoalState,
    GrowthConfig,
    GrowthTrigger,
    GrowthType,
    Namespace,
    TraitConstraint,
    TraitValue,
    TriggerDirection,
    Visibility,
)
from magick_mind.models.v1.project import (
    CreateProjectRequest,
    GetProjectListResponse,
    Project,
    UpdateProjectRequest,
)
from magick_mind.models.v1.runtime import (
    EffectivePersonality,
    EffectiveSources,
    EffectiveTrait,
)
from magick_mind.models.v1.trait import (
    CategoricalConfig,
    CreateTraitRequest,
    ListTraitsResponse,
    LockType,
    MultilabelConfig,
    NumericConfig,
    PatchTraitRequest,
    Trait,
    TraitNamespace,
    TraitType,
    TraitVisibility,
    UpdateTraitRequest,
)


__all__ = [
    # Chat
    "ChatSendRequest",
    "ChatAck",
    "ChatSendResponse",
    "ChatHistoryMessage",
    "HistoryResponse",
    # Project
    "Project",
    "CreateProjectRequest",
    "UpdateProjectRequest",
    "GetProjectListResponse",
    # End user
    "EndUser",
    "ParticipantType",
    "CreateEndUserRequest",
    "AttachPersonaRequest",
    "SetAgentPersonaVersionRequest",
    "MintEndUserTokenRequest",
    "MintEndUserTokenResponse",
    "RefreshEndUserTokenRequest",
    "RevokeEndUserTokenRequest",
    "RevokeEndUserTokenResponse",
    "QueryEndUserResponse",
    "UpdateEndUserRequest",
    # Episode
    "EndUserProcessEpisodeRequest",
    "ProcessEpisodeRequest",
    "ProcessEpisodeResponse",
    "Episode",
    "SearchEpisodesResponse",
    "ListEpisodesByDateRangeResponse",
    # Artifact
    "Artifact",
    "ArtifactStatusEnum",
    "DownloadUrlResponse",
    "PresignArtifactRequest",
    "PresignArtifactResponse",
    "ScopedPresignRequest",
    "GetArtifactResponse",
    "ListArtifactsResponse",
    "DeleteArtifactResponse",
    "FinalizeArtifactRequest",
    "FinalizeArtifactResponse",
    "ArtifactWebhookPayload",
    # Corpus
    "Corpus",
    "CreateCorpusRequest",
    "ListCorpusResponse",
    "UpdateCorpusRequest",
    "AddArtifactsRequest",
    "AddArtifactsResponse",
    "ArtifactStatus",
    "ListArtifactStatusesResponse",
    "IngestionStatus",
    "CorpusArtifactItem",
    "QueryCorpusResponse",
    "Entity",
    "Relationship",
    "Chunk",
    "Reference",
    "QueryMetadata",
    # API keys
    "ApiKey",
    "KeyResponse",
    "CreateApiKeyRequest",
    "CreateApiKeyResponse",
    "ListApiKeysResponse",
    "UpdateApiKeyRequest",
    "UpdateApiKeyResponse",
    "DeleteApiKeyResponse",
    # Personality primitives
    "Namespace",
    "Visibility",
    "GrowthType",
    "TriggerDirection",
    "LockType",
    "BlueprintTrait",
    "Boundary",
    "Constraint",
    "DomainRates",
    "DyadicConfig",
    "GoalState",
    "GrowthConfig",
    "GrowthTrigger",
    "TraitConstraint",
    "TraitValue",
    # Blueprint
    "Blueprint",
    "CreateBlueprintRequest",
    "UpdateBlueprintRequest",
    "PatchBlueprintRequest",
    "CloneBlueprintRequest",
    "ValidateBlueprintRequest",
    "BlueprintValidationError",
    "ValidateBlueprintResponse",
    "HydratedBlueprintTrait",
    "HydratedBlueprint",
    "ListBlueprintsResponse",
    # Mindspace
    "MindSpace",
    "MindSpaceType",
    "CreateMindSpaceRequest",
    "GetMindSpaceListResponse",
    "UpdateMindSpaceRequest",
    "AddMindSpaceUsersRequest",
    "MindspaceMessagesResponse",
    "ChatHistoryItem",
    "ChatHistoryParams",
    "CorpusChunk",
    "CorpusInfo",
    "CorpusParams",
    "FetcherParams",
    "SendMessageRequest",
    "EndUserSendMessageRequest",
    "MessageType",
    "SIGNAL_MESSAGE_TYPES",
    "CONTROL_MESSAGE_TYPES",
    "is_signal_message",
    "is_control_message",
    "ContextPrepareResponse",
    "LivekitTokenResponse",
    "LivekitJoinResponse",
    # Persona
    "Persona",
    "CreatePersonaRequest",
    "UpdatePersonaRequest",
    "CreatePersonaFromBlueprintRequest",
    "PersonaVersion",
    "CreatePersonaVersionRequest",
    "PersonaWithVersion",
    "PreparePersonaRequest",
    "PrepareAgentPersonaResponse",
    "PreparePersonaResponse",
    "ListPersonaVersionsResponse",
    # Runtime
    "EffectiveSources",
    "EffectiveTrait",
    "EffectivePersonality",
    # Trait
    "CategoricalConfig",
    "CreateTraitRequest",
    "ListTraitsResponse",
    "MultilabelConfig",
    "NumericConfig",
    "PatchTraitRequest",
    "Trait",
    "TraitNamespace",
    "TraitType",
    "TraitVisibility",
    "UpdateTraitRequest",
]
